### ISSUE TITLE
Invalid configuration object

### ISSUE THREAD

**Issue by umang-amex** [RGRjs/rgrjs.com#9]
```
$ npm run build

 rgrjs@1.0.0 build /Users/upahw/Documents/Alpha-App/rgrjs
 webpack

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'loaders'. These properties are valid:
   object { defaultRules?, exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, noParse?, rules?, strictExportPresence?, strictThisContextOnImports?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   -> Options affecting the normal modules (`NormalModuleFactory`).
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rgrjs@1.0.0 build: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rgrjs@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/$user/.npm/_logs/2020-06-18T12_21_08_413Z-debug.log
```

**Comment by umang-amex** [comment]
This is the log file
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/12.12.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.12.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle rgrjs@1.0.0~prebuild: rgrjs@1.0.0
6 info lifecycle rgrjs@1.0.0~build: rgrjs@1.0.0
7 verbose lifecycle rgrjs@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle rgrjs@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/upahw/Documents/Alpha-App/rgrjs/node_modules/.bin:/Users/upahw/.sdkman/candidates/kotlin/current/bin:/Users/upahw/.sdkman/candidates/java/current/bin:/usr/local/opt/ruby/bin:/usr/local/opt/openssl/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/bin:/Users/upahw/Library/Android/sdk/tools/bin:/Users/upahw/Library/Android/sdk/tools:/Users/upahw/Library/Android/sdk/platform-tools:/Users/upahw/Documents/development/flutter/bin
9 verbose lifecycle rgrjs@1.0.0~build: CWD: /Users/upahw/Documents/Alpha-App/rgrjs
10 silly lifecycle rgrjs@1.0.0~build: Args: [ '-c', 'webpack' ]
11 silly lifecycle rgrjs@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle rgrjs@1.0.0~build: Failed to exec build script
13 verbose stack Error: rgrjs@1.0.0 build: `webpack`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid rgrjs@1.0.0
15 verbose cwd /Users/upahw/Documents/Alpha-App/rgrjs
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/Cellar/node/12.12.0/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v12.12.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error rgrjs@1.0.0 build: `webpack`
22 error Exit status 1
23 error Failed at the rgrjs@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
